# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0

    goos:
      - linux

    goarch:
      - 386
      - amd64

    hooks:
      post: /bin/bash upx.sh

env_files:
  github_token: ~/.config/goreleaser/github_token_custom

archives:
  - replacements:
      linux: Linux
      386: i386
      amd64: x86_64

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
